### All persons
http://localhost:3001/api/persons

### Heroku DB
https://agile-falls-64774.herokuapp.com/api/persons

### Valid single person 
http://localhost:3001/api/persons/1

### Invalid single person 
http://localhost:3001/api/persons/0
